Patterns and flags
javascript-tutorial/zh-hant.javascript.info pull request #135
Opened 2021-04-12 08:46 UTC by fixiabis

## Target chapter

#### `9-regular-expressions/01-regexp-introduction`

 ## Modified files

 File name | Change（reason）
-|-
`article.md` | 翻譯繁體中文

2021-04-12 08:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/zh-hant.javascript.info?pullRequest=135) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/zh-hant.javascript.info?pullRequest=135) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/zh-hant.javascript.info?pullRequest=135) it.</sub>

2021-04-12 10:53 UTC, lenchen1112 approved these changes
Thanks for your efforts :)

2021-04-12 14:28 UTC, lenchen1112 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +一個正規表達式（又稱 "regexp"，或只寫做 "reg"）由一個**樣式**與可選用的**旗標**組成。
```suggestion
一個正規表達式（又稱 "regexp"，或只寫做 "reg"）由一個 **樣式** 與可選用的 **旗標** 組成。
```

2021-04-12 14:33 UTC, lenchen1112 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +搜尋
```suggestion
`pattern:g`：使用這個旗標會使搜尋查找所有匹配結果, 沒有這個的話 -- 只有第一個匹配結果會傳回。
```

2021-04-12 14:33 UTC, lenchen1112 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +`pattern:m`：多行模式 (介紹在此章節 <info:regexp-multiline-mode>)。
```suggestion
`pattern:m`：多行模式 (在此章節 <info:regexp-multiline-mode> 介紹)。
```

2021-04-12 14:34 UTC, lenchen1112 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +`pattern:s`：啟用 "dotAll" 模式, 允許句點符號 `pattern:.` 去匹配換行字元 `\n`（介紹在此章節 <info:regexp-character-classes>）。
```suggestion
`pattern:s`：啟用 "dotAll" 模式, 允許句點符號 `pattern:.` 去匹配換行字元 `\n`（在此章節 <info:regexp-character-classes> 介紹）。
```

2021-04-12 14:35 UTC, lenchen1112 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +`pattern:u`：啟用完整 unicode 支援。該旗標啟用了正確的代理對（surrogate pairs）處理。關於更多在此章節 <info:regexp-unicode>。
```suggestion
`pattern:u`：啟用完整 unicode 支援。該旗標啟用了正確的代理對（surrogate pairs）處理。關於更多在此章節 <info:regexp-unicode>。
```
```suggestion
`pattern:u`：啟用完整 unicode 支援。該旗標啟用了正確的代理對（surrogate pairs）處理。關於更多資訊會列在此章節 <info:regexp-unicode>。
```

2021-04-12 14:36 UTC, lenchen1112 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +`pattern:y`："Sticky" 模式：搜尋在文本中的確切位置（介紹在此章節 <info:regexp-sticky>）
```suggestion
`pattern:y`："Sticky" 模式：搜尋在文本中的確切位置（在此章節 <info:regexp-sticky> 介紹）
```

2021-04-12 14:37 UTC, lenchen1112 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +`str.match(regexp)` 方法用 `regexp` 正規表達式尋找了匹配結果在整個 `str` 字串中。
```suggestion
`str.match(regexp)` 方法用 `regexp` 正規表達式尋找在整個 `str` 字串中的所有匹配結果。
```

2021-04-12 14:38 UTC, lenchen1112 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +它有3種工作模式：
```suggestion
它有3種運作模式：
```

2021-04-12 14:39 UTC, lenchen1112 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +    alert( str.match(/we/gi) ); // We,we (2 個匹配結果的部份字串在一個陣列)
```suggestion
    alert( str.match(/we/gi) ); // We,we (一個陣列內含 2 個匹配結果的部份字串)
```

2021-04-12 14:40 UTC, lenchen1112 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +    請注意兩個 `match:We` 和 `match:we` 會被找到，是因為旗標 `pattern:i` 使正規表達式不分大小寫。
```suggestion
    請注意 `match:We` 和 `match:we` 皆被找到，是因為旗標 `pattern:i` 使正規表達式不分大小寫。
```

2021-04-12 14:42 UTC, lenchen1112 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +    如果正規表達式的一部分在括号中，則陣列除了 `0` 外還會有其他索引。我們將在此章節介紹 <info:regexp-groups>。
```suggestion
    如果正規表達式的一部分在括號中，則陣列除了 `0` 外還會有其他索引。我們將在此章節介紹 <info:regexp-groups>。
```

2021-04-12 14:44 UTC, lenchen1112 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +`str.replace(regexp, replacement)` 方法用 `regexp` 找到了匹配結果，並在 `str` 字串使用 `placement` 字串取代。（如果是 `pattern:g` 旗標的話，會是全部匹配結果，反之只會是第一個）。
```suggestion
`str.replace(regexp, replacement)` 方法用 `regexp` 找到了匹配結果，並在 `str` 字串使用 `replacement` 字串取代。（如果是 `pattern:g` 旗標的話，會是全部匹配結果，反之只會是第一個）。
```

2021-04-12 14:51 UTC, lenchen1112 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +之後的章節我們將學惜更多正規表達式，通過更多的範例，了解其他方法。
```suggestion
之後的章節我們將學習更多正規表達式，經過更多的範例，了解其他方法。
```

2021-04-12 14:52 UTC, lenchen1112 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +關於方法的完整資訊提供在此文章 <info:regexp-methods>。
```suggestion
關於方法的完整資訊在此文章 <info:regexp-methods> 內提供。
```

2021-04-12 14:55 UTC, lenchen1112 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +- `str.match(regexp)` 方法用 `regexp` 正規表達式尋找了匹配結果在整個 `str` 字串中。
```suggestion
- `str.match(regexp)` 方法尋找這些匹配：若有 `pattern:g` 旗標，找到全部匹配，否則，只找第一個匹配。
```

2021-04-12 14:57 UTC, lenchen1112 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +- `str.replace(regexp, replacement)` 方法用 `regexp` 找到了匹配結果，並在 `str` 字串中使用 `placement` 字串取代。（如果是 `pattern:g` 旗標的話，會是全部匹配結果，反之只會是第一個）。
```suggestion
- `str.replace(regexp, replacement)` 方法用 `regexp` 找到了匹配結果，並在 `str` 字串中使用 `replacement` 字串取代。：若有 `pattern:g` 旗標，取代全部匹配結果，反之只取代第一個。
```

2021-04-12 14:58 UTC, lenchen1112 requested changes
Some suggestions.

2021-04-12 16:32 UTC, fixiabis commented
那個，@lenchen1112 我可以把這個 PR 關掉嗎？我想換 branch 重發

2021-04-14 10:26 UTC, fixiabis commented
/done

2021-04-17 08:48 UTC, lenchen1112 approved these changes
LGTM. @javascript-tutorial/translate-zh-hant anyone have concern?

2021-04-20 11:52 UTC, ArvinH reviewed
Hey, @fixiabis thanks for the PR.
Have you signed the CLA?
https://cla-assistant.io/javascript-tutorial/zh-hant.javascript.info?pullRequest=135

2021-04-20 12:00 UTC, fixiabis commented
Just signed.

2021-04-20 12:05 UTC, ArvinH approved these changes

2021-04-20 12:46 UTC, merged